name: flutter_big_screen
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_bloc: ^5.0.1
  auto_route: ^0.6.1
  palette_generator: ^0.2.3
  flutter_feather_icons: ^1.0.3
  ezanimation: ^0.4.0
  tinycolor: ^1.0.2
  percent_indicator: ^2.1.5
  google_fonts: ^1.1.0
  like_button: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family:  FlutterApp
      fonts:
        - asset: assets/custom_icons/fonts/FlutterApp.ttf
